#!/bin/bash
set -e

PHP_ERROR_REPORTING=${PHP_ERROR_REPORTING:-"E_ALL"}
echo "error_reporting = $PHP_ERROR_REPORTING" >> /etc/php/8.1/apache2/php.ini
echo "error_reporting = $PHP_ERROR_REPORTING" >> /etc/php/8.1/cli/php.ini

# Apache gets grumpy about PID files pre-existing
rm -f /var/run/apache2/apache2.pid

source /etc/apache2/envvars && exec /usr/sbin/apache2 -DFOREGROUND
